# Copyright 2021-2024 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Run Tests 

on:
  workflow_run:
    workflows: ["GitHub CI (basic gcc)"]
    types: [completed]

run-name: ${{ github.event.workflow.name }}

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ${{ github.server_url == 'https://github.com' && 'ubuntu-latest' || 'ubuntu-22.04-self-hosted' }}
    steps:
    - name: download build tree
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.workflow.name }}
        path: .
        run-id: ${{ github.event.workflow_run.id }}
    - name: extract artifacts
      run: |
        tar xvf "${{ github.event.workflow.name }}.tgz"
    - name: get cpu info
      run: |
        cat /proc/cpuinfo
        ./util/opensslwrap.sh version -c
    - name: make test
      run: .github/workflows/make-test
    - name: save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "ci@${{ github.event.workflow.name }}"
        path: artifacts.tar.gz
    - name: delete build artifacts
      if: always()
      uses: geekyeggo/delete-artifact@v5
      with:
        name: ${{ github.event.workflow.name }} 
        failOnError: false
