name: "Install Nasm"

on:
  workflow_dispatch:

jobs:
  runs-on: windows-latest
  steps:
    install_nasm:
      - name: "Install Nasm"
        shell: pwsh
        run: |
          winget install nasm 

